### ISSUE TITLE
module limit

### ISSUE THREAD

**Issue by xiaowei520** [xinliangnote/go-gin-api#1]
https://github.com/xiaowei520/golangx/tree/master/rate
对第三方业务进行的限流、

**Comment by xiaoxiaoyu85** [comment]
想一起加入这个项目，不知道是否愿意接受？

**Comment by xinliangnote** [comment]
> 想一起加入这个项目，不知道是否愿意接受？

可以呀，欢迎大佬的加入，微信交流吧，可以提PR。

**Comment by xiaoxiaoyu85** [comment]
> > 想一起加入这个项目，不知道是否愿意接受？
> 
> 可以呀，欢迎大佬的加入，微信交流吧，可以提PR。

大牛过奖了，也是觉得用起来挺爽的，最近也在用Gin做一个项目
