### ISSUE TITLE
trace id 的存储问题

### ISSUE THREAD

**Issue by yuwingo** [xinliangnote/go-gin-api#2]
您好 我看到trace id是通过`c.Set()`方法存储的，取的时候是调用`c.Value`吗？这样会不会有并发读写map的问题呢？

**Comment by xinliangnote** [comment]
> 您好 我看到trace id是通过`c.Set()`方法存储的，取的时候是调用`c.Value`吗？这样会不会有并发读写map的问题呢？

不会的，这里的 c 是指上线文，因为每次请求的上下文都不同。

**Comment by jisuz** [comment]
你好，请教一下我采用的是urfave/negroni+gorilla/mux框架的web服务
需要检测http->grpc client->grpc serve链路请求过程，
我找到了你的demo，参考了你的demo编写了代码，但是在opentracing.SpanContext的存储方面遇到了问题。
1.是否可以通过sync.Map来存储opentracing.SpanContext
2.在http请求中使用中间件加入jaeger然后使用sync.Map来存储opentracing.SpanContext
3.然后在grpc client中取出opentracing.SpanContext，进行下一步操作，这样子会不会存在什么问题
4.因为我用的框架没有像gin一样，自带c 上线文，每次请求的上下文都不同
请问有没有什么比较好的方案可以指导一下哈，谢谢

**Comment by xinliangnote** [comment]
> 您好 我看到trace id是通过`c.Set()`方法存储的，取的时候是调用`c.Value`吗？这样会不会有并发读写map的问题呢？

代码已优化，trace id 去掉了 Jaeger 方式，实现了内部的链路日志，文档地址：https://www.yuque.com/xinliangnote/go-gin-api/gtdxxe
