### ISSUE TITLE
接口定义疑问

### ISSUE THREAD

**Issue by colinrs** [xinliangnote/go-gin-api#24]
```
type Hash interface {
	i()

	// hashids
	HashidsEncode(params []int) (string, error)
	HashidsDecode(hash string) ([]int, error)
}
```

为何我看到在您的项目中有大量的类似这样的接口定义，i() 这个方法在实现的时候又是一个空的方法，这样做有什么含义么？

**Comment by xinliangnote** [comment]
`i()` 可以理解为是一个 小写方法，至于起什么名字都可以，目的是为了这个 `interface{}` 只能在本包被实现，不允许在其他包被实现。

**Comment by colinrs** [comment]
Go的接口在哪里被实现都可以，为什么要做这个只能在本包被实现，不允许在其他包被实现的限制？

**Comment by colinrs** [comment]
> `i()` 可以理解为是一个 小写方法，至于起什么名字都可以，目的是为了这个 `interface{}` 只能在本包被实现，不允许在其他包被实现。

Go的接口在哪里被实现都可以，为什么要做这个只能在本包被实现，不允许在其他包被实现的限制？

**Comment by xinliangnote** [comment]
> > `i()` 可以理解为是一个 小写方法，至于起什么名字都可以，目的是为了这个 `interface{}` 只能在本包被实现，不允许在其他包被实现。
> 
> Go的接口在哪里被实现都可以，为什么要做这个只能在本包被实现，不允许在其他包被实现的限制？

如果接口中定义的方法全为大写方法，是可以被其他包实现的，如果定义了小写方法其他包是不能实现的。

现在这样写是遵循自己定义的项目规范，例如 admin_handler 中定义的接口，只能在 admin_hander 包中去实现，这样便于后期维护代码。
