### ISSUE TITLE
使用代码生成器错误，授权调用方不是太理解

### ISSUE THREAD

**Issue by JokerFy** [xinliangnote/go-gin-api#31]
使用代码生成器：
'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by huatianxin** [comment]
> 使用代码生成器：
> '.' 不是内部或外部命令，也不是
> 可运行的程序或批处理文件。

这个问题解决了吗？

**Comment by xinliangnote** [comment]
> > 使用代码生成器：
> > '.' 不是内部或外部命令，也不是
> > 可运行的程序或批处理文件。
> 
> 这个问题解决了吗？

我这边没有复现这个问题，加我下微信，我帮你排查下吧。

**Comment by xinliangnote** [comment]
> 使用代码生成器：
> '.' is not recognized as an internal or external command,
> operable program or batch file.

下载最新代码试一下，如果还存在问题，可以加我下微信，我帮你排查。

**Comment by anserme** [comment]
> > 使用代码生成器：
> > '.' 不是内部或外部命令，也不是
> > 可运行的程序或批处理文件。
> 
> 这个问题解决了吗？

在最近的commit中已经修复了这个问题，您可以pull后尝试。
