### ISSUE TITLE
Go Version 不满足要求

### ISSUE THREAD

**Issue by zhouruisong** [xinliangnote/go-gin-api#32]
我本地golang版本是1.16, 为什么在运行时还是提示Go Version 不满足要求?

检测环境
所需版本： Go Version go1.15+，目前版本：go1.16.3。

**Comment by xinliangnote** [comment]
> 我本地golang版本是1.16, 为什么在运行时还是提示Go Version 不满足要求?
> 
> 检测环境
> 所需版本： Go Version go1.15+，目前版本：go1.16.3。

bug 已修复，请拉取最新代码。

**Comment by xinliangnote** [comment]
> 我的也是
> 所需版本： Go Version go1.15+，目前版本：go1.16.4。

bug 已修复，请拉取最新代码。
