### ISSUE TITLE
怎么新建接口啊

### ISSUE THREAD

**Issue by haobanz** [xinliangnote/go-gin-api#36]
小白还太笨了 不会看 又找不到相关文档

**Comment by xinliangnote** [comment]
比这 `internal/api/controller/admin_handler` 写就行了。

我在考虑要不要录视频教程？！

**Comment by haobanz** [comment]
- 我觉得可以 B站来一波**🤣**

**Comment by huatianxin** [comment]
代码生成工具使用后直接报错
【'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���】
乱码

**Comment by xinliangnote** [comment]
> 代码生成工具使用后直接报错
> 【'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
> ���������ļ���】
> 乱码

我这边没有复现这个问题，加我下微信，我帮你排查下吧。

**Comment by gofromzero** [comment]
> > 代码生成工具使用后直接报错
> > 【'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
> > ���������ļ���】
> > 乱码
> 
> 我这边没有复现这个问题，加我下微信，我帮你排查下吧。

请问这个解决了吗 我也是出现这种问题

**Comment by xinliangnote** [comment]
> > > 代码生成工具使用后直接报错
> > > 【'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
> > > ���������ļ���】
> > > 乱码
> > 
> > 
> > 我这边没有复现这个问题，加我下微信，我帮你排查下吧。
> 
> 请问这个解决了吗 我也是出现这种问题

下载最新代码试一下，如果还存在问题，可以加我下微信，我帮你排查。

**Comment by xinliangnote** [comment]
> 代码生成工具使用后直接报错
> 【'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
> ���������ļ���】
> 乱码

下载最新代码试一下，如果还存在问题，可以加我下微信，我帮你排查。

**Comment by gofromzero** [comment]
最新的还是有问题 主要是 win 下的反斜杠路径 ， 还有 gormgen.sh 如果是在win环境下  生成的gormgen 文件 需要加上.exe 才能运行

**Comment by anserme** [comment]
> > > 代码生成工具使用后直接报错
> > > 【'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
> > > ���������ļ���】
> > > 乱码
> > 
> > 
> > 我这边没有复现这个问题，加我下微信，我帮你排查下吧。
> 
> 请问这个解决了吗 我也是出现这种问题

在最近的commit中已经修复了

**Comment by iusn** [comment]
能有个详细的文档就更好了👍🏻
