### ISSUE TITLE
go run main.go -env fat  // -env fat 设置为测试环境    ，之后完之后 没有进入到服务初始化界面。是什么问题

### ISSUE THREAD

**Issue by kongdekede** [xinliangnote/go-gin-api#38]
安装完之后  http://127.0.0.1:9999/ 首页打不开呢

**Comment by kongdekede** [comment]
健康检查接口
promsus监控都是正常的，就是没找到服务启动的配置页

**Comment by xinliangnote** [comment]
> 安装完之后 http://127.0.0.1:9999/ 首页打不开呢

看下浏览器有拦截窗口吗？安装完之后，可以通过这个地址登录： http://127.0.0.1:9999/login

**Comment by kongdekede** [comment]
> > 安装完之后 http://127.0.0.1:9999/ 首页打不开呢
> 
> 看下浏览器有拦截窗口吗？安装完之后，可以通过这个地址登录： http://127.0.0.1:9999/login

@xinliangnote 没有被拦，通过这个地址登录： http://127.0.0.1:9999/login  也是404 page not found

**Comment by xinliangnote** [comment]
> > > 安装完之后 http://127.0.0.1:9999/ 首页打不开呢
> > 
> > 
> > 看下浏览器有拦截窗口吗？安装完之后，可以通过这个地址登录： http://127.0.0.1:9999/login
> 
> @xinliangnote 没有被拦，通过这个地址登录： http://127.0.0.1:9999/login 也是404 page not found

是不是还没进入到初始化界面？初始化界面地址：http://127.0.0.1:9999/install，初始化成功后，打开登录界面地址：http://127.0.0.1:9999/login，如果还有问题，可以加我微信。

**Comment by kongdekede** [comment]
@xinliangnote 
http://127.0.0.1:9999/install 页面也是 404 page not found

项目启动前，有什么是必须配置的嘛？？
您的微信是多少

**Comment by xinliangnote** [comment]
微信沟通结果：因为代码是旧版，使用最新版代码，问题已解决。
