### ISSUE TITLE
我可以参加您的项目构建书写吗？

### ISSUE THREAD

**Issue by php2go** [xinliangnote/go-gin-api#4]
我可以参加您的项目构建书写吗？

**Comment by xinliangnote** [comment]
可以编写英文的吗？在这个 issue 中已经有两人提出了。。。 https://github.com/xinliangnote/go-gin-api/issues/30

**Comment by anserme** [comment]
我可以协助您将项目文档翻译成英文

**Comment by xinliangnote** [comment]
> 我可以协助您将项目文档翻译成英文

哇，太好了，加我微信吧。
