### ISSUE TITLE
gin自带的参数校验组件不可用

### ISSUE THREAD

**Issue by ihaveadrame** [xinliangnote/go-gin-api#45]
如题， 我在尝试给request的结构体定义校验规则时，发生了校验失效的问题，当我debug时发现默认的校验器没有初始化。

**Comment by xinliangnote** [comment]
> 如题， 我在尝试给request的结构体定义校验规则时，发生了校验失效的问题，当我debug时发现默认的校验器没有初始化。

1.确认下，是最新的代码吗？
2.贴一下代码吧。
