### ISSUE TITLE
缓存清理，数据一致性

### ISSUE THREAD

**Issue by GLTSC** [xinliangnote/go-gin-api#50]
更改了用户菜单授权，redis中的缓存没有清理掉，导致权限从页面看不生效——数据不一致
手动清理掉redis的缓存后，未命中的情况下没有再去mysql从新缓存数据

**Comment by xinliangnote** [comment]
> 更改了用户菜单授权，redis中的缓存没有清理掉，导致权限从页面看不生效——数据不一致
> 手动清理掉redis的缓存后，未命中的情况下没有再去mysql从新缓存数据

给用户更改了菜单授权时，需要让该用户主动退出再重新登录 或 在后台操作该用户下线再让用户重新登录。

**Comment by GLTSC** [comment]
OK，明白了
