### ISSUE TITLE
有没有集成websocket呢

### ISSUE THREAD

**Issue by bing127** [xinliangnote/go-gin-api#51]

**Comment by xinliangnote** [comment]
目前没有集成。
如果使用 websocket ，推荐使用这个组件：https://github.com/gorilla/websocket

**Comment by bing127** [comment]
> 目前没有集成。
> 如果使用 websocket ，可以了解下这个组件：https://github.com/gorilla/websocket

有没有计划支持了

有没有计划支持了

**Comment by xinliangnote** [comment]
> > 目前没有集成。
> 
> > 如果使用 websocket ，可以了解下这个组件：https://github.com/gorilla/websocket
> 
> 
> 
> 有没有计划支持了
> 
> 
> 
> 有没有计划支持了
> 
> 

有计划

**Comment by xinliangnote** [comment]
已集成 websocket，实用工具箱 -> WebSocket 栏目，在界面中可以发送消息。
