### ISSUE TITLE
请问代码生成器是不是不能用了?

### ISSUE THREAD

**Issue by diy0663** [xinliangnote/go-gin-api#60]
点击生成数据表 CURD 的时候,
http://127.0.0.1:9999/generator/gorm/execute
Request Method: POST
Status Code: 200 OK

接口返回了 "" ,没有发现报错

**Comment by xinliangnote** [comment]
可以用的，是最新代码吗？可以加下我微信，多发我一些信息，例如界面截图、日志等我来帮你定位下问题。

**Comment by xinliangnote** [comment]
> 点击生成数据表 CURD 的时候, http://127.0.0.1:9999/generator/gorm/execute Request Method: POST Status Code: 200 OK
> 
> 接口返回了 "" ,没有发现报错

可以用的，是最新代码吗？可以加下我微信，多发我一些信息，例如界面截图、日志等我来帮你定位下问题。

**Comment by diy0663** [comment]
问题已解决,主要是环境问题,跑的docker用  golang:1.16-alpine ,
 在命令行执行上 报 sh: ./gormgen.sh not found
通过安装 bash shell 去解决,参考: https://www.136.la/nginx/show-109998.html

后面假如 遇到  "/bin/bash: go-gin-api/scripts/gormgen.sh: /bin/bash^M: bad interpreter: No such file or directory\n"
靠 执行 sed -i -e 's/\r$//' gormgen.sh 解决 ,参考: https://stackoverflow.com/questions/14219092/bash-script-and-bin-bashm-bad-interpreter-no-such-file-or-directory

**Comment by diy0663** [comment]
感谢作者的耐心指导 @xinliangnote

**Comment by CherishMvp** [comment]
![image](https://github.com/xinliangnote/go-gin-api/assets/88085841/849b44b9-2833-4147-9800-45492df24c4c)
