### ISSUE TITLE
建议支持多种数据库：例如Postgresql和Oracle

### ISSUE THREAD

**Issue by Snax1210** [xinliangnote/go-gin-api#61]
以下基于commit：9aa0067e07d036b4ae57168d2bd138d142dff80e
建议使用gorm在程序初始化的时候创建表，eg:
```go
type User struct {
	//通过在字段后面的标签说明，定义golang字段和表字段的关系
	//例如 `gorm:"column:username"` 标签说明含义是: Mysql表的列名（字段名)为username
	//这里golang定义的Username变量和MYSQL表字段username一样，他们的名字可以不一样。
	Id int64 `gorm:"column:username;not null;type:int(4) primary key auto_increment;comment:'用户名'"`
	Password string `gorm:"column:password;type:varchar(30);index:idx_name"`
	//创建时间，时间戳
	CreateTime int64 `gorm:"column:createtime"`
}
```
同时建议不要在代码中直接写sql
eg:internal/api/controller/tool_handler/func_tables.go:48
切换数据库的时候很痛苦
（postgres要在连接的时候指定数据库，Oracle要在连接的时候指定用户）
谢谢

**Comment by xinliangnote** [comment]
> 以下基于commit：9aa0067e07d036b4ae57168d2bd138d142dff80e 建议使用gorm在程序初始化的时候创建表，eg:
> 
> ```go
> type User struct {
> 	//通过在字段后面的标签说明，定义golang字段和表字段的关系
> 	//例如 `gorm:"column:username"` 标签说明含义是: Mysql表的列名（字段名)为username
> 	//这里golang定义的Username变量和MYSQL表字段username一样，他们的名字可以不一样。
> 	Id int64 `gorm:"column:username;not null;type:int(4) primary key auto_increment;comment:'用户名'"`
> 	Password string `gorm:"column:password;type:varchar(30);index:idx_name"`
> 	//创建时间，时间戳
> 	CreateTime int64 `gorm:"column:createtime"`
> }
> ```
> 
> 同时建议不要在代码中直接写sql eg:internal/api/controller/tool_handler/func_tables.go:48 切换数据库的时候很痛苦 （postgres要在连接的时候指定数据库，Oracle要在连接的时候指定用户） 谢谢

sorry，目前还不支持，主要是因为作者不会。
