### ISSUE TITLE
panic时发送的邮件模板多了一个}

### ISSUE THREAD

**Issue by wujiangfa-xlauncher** [xinliangnote/go-gin-api#62]
问题：panic时发送的邮件模板多了一个}，
文件位置：internal/pkg/notify/templates/panic-mail.go
![image](https://user-images.githubusercontent.com/53930349/142128907-e3703b73-6fbd-4a1f-b6a1-4c1531dcd089.png)

**Comment by xinliangnote** [comment]
> 问题：panic时发送的邮件模板多了一个}， 文件位置：internal/pkg/notify/templates/panic-mail.go ![image](https://user-images.githubusercontent.com/53930349/142128907-e3703b73-6fbd-4a1f-b6a1-4c1531dcd089.png)

收到，已修改完毕。
