### ISSUE TITLE
少了个跨域中间件吧

### ISSUE THREAD

**Issue by wisonlau** [xinliangnote/go-gin-api#63]
在login页面调用/api/login接口直接跨域了

```
package middleware

import (
	"collectlogs/internal/pkg/core"
)

type HandlerFunc func()

// 处理跨域请求,支持options访问
func (m *middleware) Cors() core.HandlerFunc {
	return func(c core.Context) {
		c.SetHeader("Access-Control-Allow-Origin", "*")
		c.SetHeader("Access-Control-Allow-Headers", "Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id")
		c.SetHeader("Access-Control-Allow-Methods", "POST, GET, OPTIONS,DELETE,PUT")
		c.SetHeader("Access-Control-Expose-Headers", "Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type")
		c.SetHeader("Access-Control-Allow-Credentials", "true")

		return
	}
}
```

还有一个问题就是放在路由下的中间件,我不写调用方法都直接被调用了.感觉这样不太好.

**Comment by xinliangnote** [comment]
> 在login页面调用/api/login接口直接跨域了
> 
> ```
> package middleware
> 
> import (
> 	"collectlogs/internal/pkg/core"
> )
> 
> type HandlerFunc func()
> 
> // 处理跨域请求,支持options访问
> func (m *middleware) Cors() core.HandlerFunc {
> 	return func(c core.Context) {
> 		c.SetHeader("Access-Control-Allow-Origin", "*")
> 		c.SetHeader("Access-Control-Allow-Headers", "Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id")
> 		c.SetHeader("Access-Control-Allow-Methods", "POST, GET, OPTIONS,DELETE,PUT")
> 		c.SetHeader("Access-Control-Expose-Headers", "Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type")
> 		c.SetHeader("Access-Control-Allow-Credentials", "true")
> 
> 		return
> 	}
> }
> ```
> 
> 还有一个问题就是放在路由下的中间件,我不写调用方法都直接被调用了.感觉这样不太好.

目前是支持跨域的，详见：https://www.yuque.com/xinliangnote/go-gin-api/lcvpix
