### ISSUE TITLE
build 后直接执行报错

### ISSUE THREAD

**Issue by ohmygods** [xinliangnote/go-gin-api#71]
问题描述
go build 编译出 main 后直接执行 main ，系统报错
`./main -env fat

2022/03/08 02:03:10 /.../go-gin-api/internal/repository/mysql/mysql.go:96
[error] failed to initialize database, got error Error 1045: Access denied for user 'root'@'172.17.0.1' (using password: YES)`

问题出现的环境背景及自己尝试过哪些方法
系统环境是 linux mint (ubuntu)
如果执行 go run main.go 是成功的，但是编译后执行就失败。
报错信息中显示的 172.17.0.1 地址是docker网卡地址，说明它没有找到正确的配置文件

**Comment by imlida** [comment]
遇到相同问题
