### ISSUE TITLE
var _ Handler = (*handler)(nil)  请问大佬这句啥意思？

### ISSUE THREAD

**Issue by yanggangying** [xinliangnote/go-gin-api#74]
代码里面很多类似这样的语句var _ Handler = (*handler)(nil)  这句啥意思 ，实在是很想知道这句啥意思？

**Comment by yanggangying** [comment]
检查handler这个struct是否实现了Handler这个接口

**Comment by zxllovexu** [comment]
编译阶段对handler接口实现的检查

**Comment by xinliangnote** [comment]
如你所说是这个意思，可以看下这篇文章：https://mp.weixin.qq.com/s/gpMzEoRofGE9LmayeYw1qw
