### ISSUE TITLE
用于生产环境会出什么问题

### ISSUE THREAD

**Issue by zjfsdnu** [xinliangnote/go-gin-api#76]
供参考学习，线上使用请谨慎！
用于生产环境会出什么问题啊?
有用上的吗?

**Comment by xinliangnote** [comment]
本项目未进行严谨的测试验证，仅仅是开发者自测，项目中也缺少 单元测试、验收测试 等。
- 如果上线项目要求严格的话，建议谨慎！
- 如果上线项目要求没那么严格，自测后没问题，可以线上使用。
