### ISSUE TITLE
x509: failed to load system roots and no roots provided; SecTrustSettingsCopyCertificates error: -25300

### ISSUE THREAD

**Issue by forging2012** [xinliangnote/go-gin-api#8]
go run main.go -env fat 
go: github.com/99designs/gqlgen@v0.13.0: Get "https://goproxy.io/github.com/99designs/gqlgen/@v/v0.13.0.mod": x509: failed to load system roots and no roots provided; SecTrustSettingsCopyCertificates error: -25300

**Comment by xinliangnote** [comment]
看下这篇文章，https://studygolang.com/articles/11428
