### ISSUE TITLE
有集合各个组件用法的example吗?

### ISSUE THREAD

**Issue by ruanhanqin** [xinliangnote/go-gin-api#9]

**Comment by xinliangnote** [comment]
详细文档：https://www.yuque.com/xinliangnote/go-gin-api/ngc3x5

**Comment by ruanhanqin** [comment]
上面没写怎么用的demo

**Comment by xinliangnote** [comment]
> 上面没写怎么用的demo

每个组件中都有示例代码，例如 `生成 swagger 接口文档` ：https://www.yuque.com/xinliangnote/go-gin-api/fqe4yx
